### ISSUE TITLE
Pass grace period to ProposalCard->OffchainVotingStatus for display on listings

### ISSUE THREAD

**Issue by jtrein** [openlawteam/tribute-ui#203]
Currently, the grace period timer will not show in the listing page(s) cards. Not a huge deal, but should add it in order to be consistent with the details page(s).

- [x] Fetch grace period for a proposal
- [x] Pass grace period through `ProposalCard->OffchainVotingStatus`

**Comment by jdville03** [comment]
Resolved in #420
