### ISSUE TITLE
Enforce HTTPS in GH Pages

### ISSUE THREAD

**Issue by jtrein** [openlawteam/tribute-ui#307]
- [x] Enforce HTTPS in tribute-ui repo

**Comment by jdville03** [comment]
I think the easiest thing to do for now is to utilize this GH pages feature where it only serves https. It's not clickable yet but that was my plan.

![Uploading Screen Shot 2021-05-05 at 9.10.34 AM.png…]()

**Comment by jdville03** [comment]
This is done now. http://tributedao.com will direct to https://tributedao.com.
