### ISSUE TITLE
Improve UX for user that just received membership units for the first time.

### ISSUE THREAD

**Issue by jdville03** [openlawteam/tribute-ui#339]
When a user is connected and completes a transaction that issues them their first membership units (e.g., their previous balance was 0 before they processed their onboarding proposal or redeemed a coupon), the user must do a hard refresh in order to be "recognized" as a member and be able to view members only features. Ideally, the user shouldn't have to do the hard refresh and should have full access as a new member.

**Comment by jtrein** [comment]
Good idea. We should be able to re-fetch the member using the `await getConnectedMember` action after any successful membership tx completes.
