### ISSUE TITLE
Offchain Proof Helpers

### ISSUE THREAD

**Issue by fforbeck** [openlawteam/tribute-ui#459]
I was wondering if it makes sense to move the helpers from tribute-ui to snapshot-erc712-js

- [submitOffchainVotingProof](https://github.com/openlawteam/tribute-ui/blob/main/src/components/proposals/helpers/submitOffchainVotingProof.ts)
- [getOffchainVotingProof](https://github.com/openlawteam/tribute-ui/blob/main/src/components/proposals/helpers/getOffchainVotingProof.ts)

cc @jtrein

**Comment by jdville03** [comment]
Resolved by openlawteam/snapshot-js-erc712#35
