### ISSUE TITLE
Member details ENS/Ethereum address display font typeface 

### ISSUE THREAD

**Issue by sophiacodes** [openlawteam/tribute-ui#509]
ENS/Ethereum address is not displaying correctly on the members details page. 

Ethereum Address:
<img width="692" alt="Screenshot 2021-12-14 at 11 50 03" src="https://user-images.githubusercontent.com/2333082/145993222-e1632d74-4428-4caf-97af-f6049a41cf56.png">

ENS:
<img width="682" alt="Screenshot 2021-12-14 at 11 50 35" src="https://user-images.githubusercontent.com/2333082/145993233-151c4998-cbc7-4696-9196-26d8a1c1f239.png">

**Comment by jtrein** [comment]
Looks to be affecting Neon only. Perhaps we need a `line-height` added to the styles.

**Comment by jdville03** [comment]
I'll fix this in Neon today when I do another upstream sync and deploy for it. I had to fix some other similar style bugs with it yesterday. Neon has some little quirks that aren't consistent with all the other DAO styles. Not sure why that is.
